### ISSUE TITLE
Error when iOS simulating because of a swift compiler 

### ISSUE THREAD

**Issue by workfluo** [akofman/cordova-plugin-dbmeter#1]
To have this plugin installed (without using it or even mentioning it in config.xml) is enough to create a build fail for iOS but for iOS only (for android the problemes come after with a blacked screen).

Here is some of the error outputs
** BUILD FAILED **
The following build commands failed:
CompileSwift normal i386 /Users/Workfluo/ionic-server/wad/platforms/ios/What a Day/Plugins/cordova-plugin-dbmeter/DBMeter.swift

CompileSwiftSources normal i386 com.apple.xcode.tools.swift.compiler

(2 failures)

Error: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/Workfluo/ionic-server/wad/platforms/ios/cordova/build-debug.xcconfig,-project,What a Day.xcodeproj,ARCHS=i386,-target,WaD,-configuration,Debug,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/Users/Workfluo/ionic-server/wad/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/Workfluo/ionic-server/wad/platforms/ios/build/sharedpch

**Comment by akofman** [comment]
Hello,

My first guess is that you should add `<preference name="UseLegacySwiftLanguageVersion" value="true" />`in the `config.xml` of your app as it is mentioned in the README.

If it doesn't work, could you show me all the stack because it's quite difficult to get it with such a few info.

**Comment by workfluo** [comment]
Did it.
Here are the all error text
2016-12-21 10:33:37.229 xcodebuild[22708:30b]  DVTAssertions: Warning in /SourceCache/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-6245/Xcode3Core/LegacyProjects/Frameworks/DevToolsCore/DevToolsCore/SpecificationTypes/BuiltInSpecifications/Compilers/XCGccMakefileDependencies.m:77
Details:  Failed to load dependencies output contents from ``/Users/Workfluo/ionic-server/wad/platforms/ios/build/What a Day.build/Debug-iphonesimulator/What a Day.build/Objects-normal/i386/DBMeter.d''. Error: Error Domain=NSCocoaErrorDomain Code=260 "The file “DBMeter.d” couldn’t be opened because there is no such file." UserInfo=0x7f8fd57384f0 {NSFilePath=/Users/Workfluo/ionic-server/wad/platforms/ios/build/What a Day.build/Debug-iphonesimulator/What a Day.build/Objects-normal/i386/DBMeter.d, NSUnderlyingError=0x7f8fd54873b0 "The operation couldn’t be completed. No such file or directory"}. User info: {
    NSFilePath = "/Users/Workfluo/ionic-server/wad/platforms/ios/build/wad.build/Debug-iphonesimulator/wad.build/Objects-normal/i386/DBMeter.d";
    NSUnderlyingError = "Error Domain=NSPOSIXErrorDomain Code=2 \"The operation couldn\U2019t be completed. No such file or directory\"";
}.
Function: void XCGccMakefileDependenciesParsePathsFromRuleFile(NSString *__strong, void (^__strong)(NSString *__strong))
Thread:   <NSThread: 0x7f8fd54dce50>{name = (null), num = 7}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.

** BUILD FAILED **



The following build commands failed:
	CompileSwift normal i386 /Users/Workfluo/ionic-server/wad/platforms/ios/wad/Plugins/cordova-plugin-dbmeter/DBMeter.swift
	CompileSwiftSources normal i386 com.apple.xcode.tools.swift.compiler
(2 failures)

Error: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/Workfluo/ionic-server/wad/platforms/ios/cordova/build-debug.xcconfig,-project,wad.xcodeproj,ARCHS=i386,-target,wad,-configuration,Debug,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/Users/Workfluo/ionic-server/wad/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/Workfluo/ionic-server/wad/platforms/ios/build/sharedpch

**Comment by Huiting-Yeong** [comment]
Hi I am also getting the same error code 65. Have you been able to solve it? I have already add `<preference name="UseLegacySwiftLanguageVersion" value="true" />` to config.xml

**Comment by workfluo** [comment]
Nope no nada, same shit.

**Comment by Huiting-Yeong** [comment]
Hey thanks for the reply. I managed to solve my problem by running `sudo npm install -g ios-deploy --unsafe-perm=true` then remove platform and add platform. I realised I needed --unsafe... for it to work. 
Maybe this will work for you also! Else can reference [https://github.com/driftyco/ionic-cli/issues/1060](url)

**Comment by kalun1988** [comment]
Added
 <preference name="UseLegacySwiftLanguageVersion" value="true" />in the config.xml

But still cannot compile on cocoon.io



COMPILER ERROR: 

Internal compiler error

CORDOVA LOG: 

Developer/Xcode/DerivedData/P-Sense-fafiagplzqqlfoaroiqjnqeankaw/Build/Intermediates/ArchiveIntermediates/P-Sense/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/libCordova.a
CreateUniversalBinary /Library/Developer/Xcode/DerivedData/P-Sense-fafiagplzqqlfoaroiqjnqeankaw/Build/Intermediates/ArchiveIntermediates/P-Sense/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/libCordova.a normal armv7\ arm64
    cd /workspace/platforms/ios/CordovaLib
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin/:/opt/cocoon_compiler/workspace/production/data/sdks/android-sdks-darwin/tools:/opt/cocoon_compiler/workspace/production/data/sdks/android-sdks-darwin/platform-tools:/Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/bin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool -static /Library/Developer/Xcode/DerivedData/P-Sense-fafiagplzqqlfoaroiqjnqeankaw/Build/Intermediates/ArchiveIntermediates/P-Sense/IntermediateBuildFilesPath/CordovaLib.build/Release-iphoneos/CordovaLib.build/Objects-normal/armv7/libCordova.a /Library/Developer/Xcode/DerivedData/P-Sense-fafiagplzqqlfoaroiqjnqeankaw/Build/Intermediates/ArchiveIntermediates/P-Sense/IntermediateBuildFilesPath/CordovaLib.build/Release-iphoneos/CordovaLib.build/Objects-normal/arm64/libCordova.a -o /Library/Developer/Xcode/DerivedData/P-Sense-fafiagplzqqlfoaroiqjnqeankaw/Build/Intermediates/ArchiveIntermediates/P-Sense/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/libCordova.a[32m[2017-02-21 21:45:15.937] [INFO] IOSBuilder - [39m
[32m[2017-02-21 21:45:15.938] [INFO] IOSBuilder - [39mStrip /Library/Developer/Xcode/DerivedData/P-Sense-fafiagplzqqlfoaroiqjnqeankaw/Build/Intermediates/ArchiveIntermediates/P-Sense/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/libCordova.a
    cd /workspace/platforms/ios/CordovaLib
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin/:/opt/cocoon_compiler/workspace/production/data/sdks/android-sdks-darwin/tools:/opt/cocoon_compiler/workspace/production/data/sdks/android-sdks-darwin/platform-tools:/Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/bin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip -S /Library/Developer/Xcode/DerivedData/P-Sense-fafiagplzqqlfoaroiqjnqeankaw/Build/Intermediates/ArchiveIntermediates/P-Sense/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/libCordova.a
Strip /Library/Developer/Xcode/DerivedData/P-Sense-fafiagplzqqlfoaroiqjnqeankaw/Build/Intermediates/ArchiveIntermediates/P-Sense/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/libCordova.a
    cd /workspace/platforms/ios/CordovaLib
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin/:/opt/cocoon_compiler/workspace/production/data/sdks/android-sdks-darwin/tools:/opt/cocoon_compiler/workspace/production/data/sdks/android-sdks-darwin/platform-tools:/Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/bin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip -S /Library/Developer/Xcode/DerivedData/P-Sense-fafiagplzqqlfoaroiqjnqeankaw/Build/Intermediates/ArchiveIntermediates/P-Sense/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/libCordova.a[32m[2017-02-21 21:45:19.282] [INFO] IOSBuilder - [39m
[32m[2017-02-21 21:45:19.284] [INFO] IOSBuilder - [39mSetOwnerAndGroup ideateca:staff /Library/Developer/Xcode/DerivedData/P-Sense-fafiagplzqqlfoaroiqjnqeankaw/Build/Intermediates/ArchiveIntermediates/P-Sense/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/libCordova.a
    cd /workspace/platforms/ios/CordovaLib
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin/:/opt/cocoon_compiler/workspace/production/data/sdks/android-sdks-darwin/tools:/opt/cocoon_compiler/workspace/production/data/sdks/android-sdks-darwin/platform-tools:/Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/bin"
    /usr/sbin/chown -RH ideateca:staff /Library/Developer/Xcode/DerivedData/P-Sense-fafiagplzqqlfoaroiqjnqeankaw/Build/Intermediates/ArchiveIntermediates/P-Sense/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/libCordova.a
SetOwnerAndGroup ideateca:staff /Library/Developer/Xcode/DerivedData/P-Sense-fafiagplzqqlfoaroiqjnqeankaw/Build/Intermediates/ArchiveIntermediates/P-Sense/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/libCordova.a
    cd /workspace/platforms/ios/CordovaLib
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin/:/opt/cocoon_compiler/workspace/production/data/sdks/android-sdks-darwin/tools:/opt/cocoon_compiler/workspace/production/data/sdks/android-sdks-darwin/platform-tools:/Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/bin"
    /usr/sbin/chown -RH ideateca:staff /Library/Developer/Xcode/DerivedData/P-Sense-fafiagplzqqlfoaroiqjnqeankaw/Build/Intermediates/ArchiveIntermediates/P-Sense/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/libCordova.a[32m[2017-02-21 21:45:19.310] [INFO] IOSBuilder - [39m
[32m[2017-02-21 21:45:19.312] [INFO] IOSBuilder - [39mSetMode u+w,go-w,a+rX /Library/Developer/Xcode/DerivedData/P-Sense-fafiagplzqqlfoaroiqjnqeankaw/Build/Intermediates/ArchiveIntermediates/P-Sense/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/libCordova.a
    cd /workspace/platforms/ios/CordovaLib
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin/:/opt/cocoon_compiler/workspace/production/data/sdks/android-sdks-darwin/tools:/opt/cocoon_compiler/workspace/production/data/sdks/android-sdks-darwin/platform-tools:/Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/bin"
    /bin/chmod -RH u+w,go-w,a+rX /Library/Developer/Xcode/DerivedData/P-Sense-fafiagplzqqlfoaroiqjnqeankaw/Build/Intermediates/ArchiveIntermediates/P-Sense/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/libCordova.a
SetMode u+w,go-w,a+rX /Library/Developer/Xcode/DerivedData/P-Sense-fafiagplzqqlfoaroiqjnqeankaw/Build/Intermediates/ArchiveIntermediates/P-Sense/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/libCordova.a
    cd /workspace/platforms/ios/CordovaLib
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin/:/opt/cocoon_compiler/workspace/production/data/sdks/android-sdks-darwin/tools:/opt/cocoon_compiler/workspace/production/data/sdks/android-sdks-darwin/platform-tools:/Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/bin"
    /bin/chmod -RH u+w,go-w,a+rX /Library/Developer/Xcode/DerivedData/P-Sense-fafiagplzqqlfoaroiqjnqeankaw/Build/Intermediates/ArchiveIntermediates/P-Sense/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/libCordova.a[32m[2017-02-21 21:45:19.333] [INFO] IOSBuilder - [39m
[32m[2017-02-21 21:45:19.392] [INFO] IOSBuilder - [39m=== BUILD TARGET P-Sense OF PROJECT P-Sense WITH CONFIGURATION Release ===
=== BUILD TARGET P-Sense OF PROJECT P-Sense WITH CONFIGURATION Release ===[32m[2017-02-21 21:45:19.393] [INFO] IOSBuilder - [39mCheck dependencies
Check dependencies[32m[2017-02-21 21:45:19.395] [INFO] IOSBuilder - [39m���Use Legacy Swift Language Version��� (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax���] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.
���Use Legacy Swift Language Version��� (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax���] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.[32m[2017-02-21 21:45:19.396] [INFO] IOSBuilder - [39m���Use Legacy Swift Language Version��� (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax���] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.
���Use Legacy Swift Language Version��� (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax���] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.[32m[2017-02-21 21:45:19.396] [INFO] IOSBuilder - [39m
[31m[2017-02-21 21:45:19.399] [ERROR] IOSBuilder - [39m** ARCHIVE FAILED **


The following build commands failed:
** ARCHIVE FAILED **


The following build commands failed:[31m[2017-02-21 21:45:19.400] [ERROR] IOSBuilder - [39mCheck dependencies
(1 failure)
Check dependencies
(1 failure)[36m[2017-02-21 21:45:19.464] [DEBUG] IOSBuilder - [39m[build] clean
[36m[2017-02-21 21:45:19.466] [DEBUG] IOSBuilder - [39m[build] remove keychain
security: SecKeychainDelete: The specified keychain could not be found.
[33m[2017-02-21 21:45:19.788] [WARN] IOSBuilder - [39mCommand failed: security delete-keychain 'B500EAE4.keychain-db'
security: SecKeychainDelete: The specified keychain could not be found.

**Comment by matrixreal** [comment]
same here cordova ios 3.9.2
![plu](https://cloud.githubusercontent.com/assets/6823974/24074276/bf965f8c-0c05-11e7-8a29-0238ebb6a88c.jpg)

**Comment by akofman** [comment]
Hello guys, I will try to reproduce and solve that this week. @matrixreal could you please tell me which version of `cordova-plugin-add-swift-support` are you using ? Did you try to reproduce that with a more recent version of `cordova-ios` ? Thanks.

**Comment by akofman** [comment]
Should be okay now with the last version (2.0.1)
