### ISSUE TITLE
volume compare from mic ?

### ISSUE THREAD

**Issue by matrixreal** [akofman/cordova-plugin-dbmeter#2]
Hi,
is it possible to compare a volume from microphone ? something like low or high volume from microphone directly when we speak (ios cordova)
thanks

**Comment by akofman** [comment]
hmmmm I'm not sure to understand well.  What do you mean by "volume from microphone" ? 
With the db values returned by this plugin, yes you can guess if someone is speaking loudly or not, is that answer your question ?

**Comment by matrixreal** [comment]
yes it's okay thank you
