### ISSUE TITLE
New Update

### ISSUE THREAD

**Issue by lightwaxx** [akofman/cordova-plugin-dbmeter#7]
Is there a newer version of this plugin? I don't think it is accurate though it returns results straight out of the box.

**Comment by lightwaxx** [comment]
Even at night, the dB level is around 20 - 40 and there is very low noise

**Comment by akofman** [comment]
Hello,
Thanks for your interest in this plugin.
I'm working on a new version but I think it's quite normal to get around 20-40 db by night. It also depends on your device and its microphone manufacturer filters.
As an idea, when someone is speaking you should get something between 55 and 65 db. For more info about noise ranging, you can refer to [this link](http://www.noisehelp.com/noise-level-chart.html).
Also the goal of this plugin is not to give you accurate values of db but mainly to observe variations.
